apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    role: alert-rules
  name: {{ template "exporter-kube-etcd.fullname" . }}
data:
{{- if .Values.prometheusRules }}
{{- $root := . }}
{{- range $key, $val := .Values.prometheusRules }}
  {{ $key }}: |-
{{ tpl $val $root | indent 4}}
{{- end }}
{{ else }}
  etcd3.rules: |-
    {{- include "etcd3.rules.yaml.tpl" . | indent 4}}
{{ end }}