apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-controller
  labels:
    controller: prometheus 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        controller: prometheus
    spec:
      containers:
       - name: prometheus-controller
         image: quay.io/coreos/prometheus-operator:latest
         resources:
           requests:
             cpu: 100m
             memory: 50Mi
           limits:
             cpu: 200m
             memory: 100Mi
