sudo: required
language: go
go:
- 1.9
services:
- docker
jobs:
  include:
  - stage: Check generated contents are up to date and code is formatted.
    script: ./scripts/check-make-generate.sh
  - stage: Build Prometheus config reloader
    script: cd contrib/prometheus-config-reloader && make build
  - stage: Ensure vendor folder matches vendor.json
    script: ./scripts/govendor-ensure.sh
  - stage: Unit tests
    script: make test
  - stage: E2e tests
    script: ./scripts/travis-e2e.sh
  - stage: E2e helm
    script: ./scripts/travis-e2e-helm.sh
