sudo: required
language: go
go:
- "1.10"
services:
- docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
jobs:
  include:
  # Check generated contents are up to date and code is formatted.
  - stage: Sanity check and unit tests
    script: ./scripts/check-make-generate.sh
  # Build Prometheus config reloader
  - script: cd contrib/prometheus-config-reloader && make build
  # Ensure vendor folder matches vendor.json
  - script: ./scripts/golang-dep-ensure.sh
  # Unit tests
  - script: make test
  - stage: E2e
    script: ./scripts/travis-e2e.sh
  - script: ./scripts/travis-e2e-helm.sh
  - stage: deploy
    script: skip
    deploy:
      provider: script
      script: make helm-sync-s3
      on:
        branch: master
  - stage: push-docker-image
    script: ./scripts/travis-push-docker-image.sh
