apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: prometheus-operator
    apps.kubernetes.io/version: v0.30.0
  name: prometheus-operator
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      apps.kubernetes.io/component: controller
      apps.kubernetes.io/name: prometheus-operator
      apps.kubernetes.io/version: v0.30.0
