apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: prometheus-operator
    apps.kubernetes.io/version: v0.29.0
  name: prometheus-operator
  namespace: default
