apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-kubernetes.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: kubelets
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "exporter-kubernetes.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  namespaceSelector:
    matchNames:
      - "default"
  endpoints:
  - port: https
    interval: 15s
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      # Skip verification until we have resolved why the certificate validation
      # for the kubelet on API server nodes fail.
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
