apiVersion: v1
data:
  prometheus.yaml: |
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - action: keep
          regex: alertmanager-main
          source_labels:
          - __meta_kubernetes_service_name
        - action: keep
          regex: monitoring
          source_labels:
          - __meta_kubernetes_namespace
        - action: keep
          regex: web
          source_labels:
          - __meta_kubernetes_endpoint_port_name
        scheme: http

    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
    - /etc/prometheus/rules/*.rules

    scrape_configs:
    - job_name: kubelets
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # Skip verification until we have resolved why the certificate validation
        # for the kubelet on API server nodes fail.
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node

    # Scrapes the endpoint lists for the Kubernetes API server, kube-state-metrics,
    # and node-exporter, which we all consider part of a default setup.
    - job_name: standard-endpoints
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # As for kubelets, certificate validation fails for the API server (node)
        # and we circumvent it for now.
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_name]
        regex: prometheus|node-exporter|kube-state-metrics
      - action: replace
        source_labels: [__meta_kubernetes_service_name]
        target_label: job

    # Scrapes the endpoint lists for the kube-dns server. Which we consider
    # part of a default setup.
    - job_name: kube-components
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - action: replace
        source_labels: [__meta_kubernetes_service_label_k8s_app]
        target_label: job
      - action: keep
        source_labels: [__meta_kubernetes_service_name]
        regex: ".*-prometheus-discovery"
      - action: keep
        source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: "http-metrics.*|https-metrics.*"
      - action: replace
        source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: "https-metrics.*"
        target_label: __scheme__
        replacement: https
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-k8s
