apiVersion: v1
description: Alertmanager instance created by the CoreOS Prometheus Operator
engine: gotpl
maintainers:
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
name: alertmanager
sources:
  - https://github.com/coreos/prometheus-operator
  - https://github.com/prometheus/alertmanager
version: 0.1.2
appVersion: "0.14.0"
home: https://github.com/prometheus/alertmanager
keywords:
- alertmanager
- monitoring
- prometheus
