apiVersion: v1
description: Alertmanager instance created by the CoreOS Prometheus Operator
engine: gotpl
maintainers:
  - name: Michael Goodness
    email: mgoodness@gmail.com
name: alertmanager
sources:
  - https://github.com/coreos/prometheus-operator
version: 0.0.4
