apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: kube-dns
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
  name: {{ template "exporter-kube-dns.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: {{ template "exporter-kube-dns.name" . }}
      component: kube-dns
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics-dnsmasq
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  - port: http-metrics-skydns
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
