description: Grafana instance for kube-prometheus
engine: gotpl
maintainers:
- email: weiwei.inf@gmail.com
  name: Wei Wei
name: grafana
sources:
- https://github.com/coreos/prometheus-operator
version: 0.0.3
