apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- if .Values.additionalRulesLabels }}
{{ toYaml .Values.additionalRulesLabels | indent 4 }}
    {{- else if .Values.additionalRulesConfigMapLabels }}       # Deprecated for .Values.additionalRulesLabels
{{ toYaml .Values.additionalRulesConfigMapLabels | indent 4 }}  # Deprecated for .Values.additionalRulesLabels
    {{- end }}
  name: {{ template "exporter-kube-controller-manager.fullname" . }}
spec:
{{- if .Values.prometheusRules }}
  groups:
{{ toYaml .Values.prometheusRules | indent 4 }}
{{ else }}
{{ include "kube-controller-manager.rules.yaml.tpl" . | indent 2}}
{{ end }}