apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-kube-controller-manager.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: kube-controller-manager
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}
  name: {{ template "exporter-kube-controller-manager.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: {{ template "exporter-kube-controller-manager.name" . }}
      component: kube-controller-manager
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      # Skip verification until we have resolved why the certificate validation
      # for the kubelet on API server nodes fail.
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
