apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-create-sm-job
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      name: {{ template "fullname" . }}-create-sm-job
    spec:
      containers:
        - name: hyperkube
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.global.hyperkube.pullPolicy }}"
          command:
            - ./kubectl
            - apply 
            - -f 
            - /tmp/servicemonitor/servicemonitor-operator.yaml
          volumeMounts:
            - mountPath: "/tmp/servicemonitor"
              name: tmp-configmap-servicemonitor
      volumes:
        - name: tmp-configmap-servicemonitor
          configMap:
            name: {{ template "fullname" . }}
      restartPolicy: OnFailure
      {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "fullname" . }}
      {{- end }}
