apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-get-tprs
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      name: {{ template "fullname" . }}-get-tprs
    spec:
      containers:
        - name: hyperkube
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.global.hyperkube.pullPolicy }}"
          command:
            - ./kubectl
            - get
            - thirdpartyresource
            - alertmanager.monitoring.coreos.com
            - prometheus.monitoring.coreos.com
            - service-monitor.monitoring.coreos.com
      restartPolicy: OnFailure
    {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "fullname" . }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
