apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "prometheus-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus-operator.fullname" . }}-get-crd
spec:
  template:
    metadata:
      labels:
        app: {{ template "prometheus-operator.name" . }}
        release: {{ .Release.Name }}
      name: {{ template "prometheus-operator.fullname" . }}-get-crd
    spec:
      containers:
        - name: hyperkube
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.global.hyperkube.pullPolicy }}"
          command:
            - ./kubectl
            - get
            {{- $apiVersion := include "prometheus-operator.apiVersion" . }}
            {{ if eq $apiVersion "monitoring.coreos.com/v1alpha1" }}
            - thirdpartyresources
            - alertmanager.monitoring.coreos.com
            - prometheus.monitoring.coreos.com
            - service-monitor.monitoring.coreos.com
            {{- else -}}
            - customresourcedefinitions
            - alertmanagers.monitoring.coreos.com
            - prometheuses.monitoring.coreos.com
            - servicemonitors.monitoring.coreos.com
            {{- end }}
      restartPolicy: OnFailure
    {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "prometheus-operator.fullname" . }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
