{{- if .Values.enableDaemonSet }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "exporter-node.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: node-exporter
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter-node.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "exporter-node.fullname" . }}
        component: node-exporter
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
          - --web.listen-address=0.0.0.0:{{ .Values.service.containerPort }}
          {{- if and .Values.container .Values.container.args }}
{{ toYaml .Values.container.args | indent 10 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.containerPort }}
              hostPort: {{ .Values.service.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- if and .Values.container .Values.container.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.container.volumeMounts | indent 10 }}
          {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ template "exporter-node.fullname" . }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      hostNetwork: true
      hostPID: true
      {{- if and .Values.container .Values.container.volumes }}
      volumes:
{{ toYaml .Values.container.volumes | indent 6 }}
      {{- end}}
{{- end }}
