apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "exporter-kube-state.fullname" . }}
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    component: kube-state
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    version: "{{ .Values.kube_state_metrics.image.tag }}"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "exporter-kube-state.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "exporter-kube-state.fullname" . }}
        component: kube-state
        release: {{ .Release.Name }}
        version: "{{ .Values.kube_state_metrics.image.tag }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.kube_state_metrics.image.repository }}:{{ .Values.kube_state_metrics.image.tag }}"
        imagePullPolicy: {{ .Values.kube_state_metrics.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.kube_state_metrics.service.internalPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.kube_state_metrics.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.kube_state_metrics.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: {{ .Chart.Name }}-addon-resizer
        image: "{{ .Values.addon_resizer.image.repository }}:{{ .Values.addon_resizer.image.tag }}"
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container={{ .Chart.Name }}
          - --cpu={{ .Values.addon_resizer.cpu }}
          - --extra-cpu={{ .Values.addon_resizer.extra_cpu }}
          - --memory={{ .Values.addon_resizer.memory }}
          - --extra-memory={{ .Values.addon_resizer.extra_memory }}
          - --acceptance-offset=5
          - --deployment={{ template "exporter-kube-state.fullname" . }}
        resources:
{{ toYaml .Values.addon_resizer.resources | indent 12 }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ template "exporter-kube-state.fullname" . }}
    {{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
