apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: kube-state
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "exporter-kube-state.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: {{ template "exporter-kube-state.name" . }}
      component: kube-state
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: {{ .Values.kube_state_metrics.service.name }}
    interval: 15s
    honorLabels: true
