{{- if and .Values.rules.specifiedInValues .Values.rules.value }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- if .Values.rulesSelector }}
{{ toYaml .Values.rulesSelector | indent 4 }}
    {{- end }}
  name: prometheus-{{ .Release.Name }}-rules
data:
{{ toYaml .Values.rules.value | indent 2 }}
{{- end }}
