apiVersion: v1
description: A Helm chart singleton for kube-state-metrics
name: exporter-kube-dns
version: 0.1.7
maintainers:
  - name: Michael Goodness
    email: mgoodness@gmail.com
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
