apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
data:
  kube-etcd.rules: |-
    # NOTE: These rules were kindly contributed by the SoundCloud engineering team.

    ### General cluster availability ###

    # alert if another failed peer will result in an unavailable cluster
    ALERT InsufficientPeers
      IF count(up{job="{{ template "fullname" . }}"} == 0) > (count(up{job="{{ template "fullname" . }}"}) / 2 - 1)
      FOR 3m
      LABELS {
        severity = "critical"
      }
      ANNOTATIONS {
        summary = "Etcd cluster small",
        description = "If one more etcd peer goes down the cluster will be unavailable",
      }

    ### HTTP requests alerts ###

    # alert if more than 1% of requests to an HTTP endpoint have failed with a non 4xx response
    ALERT HighNumberOfFailedHTTPRequests
      IF sum by(method) (rate(etcd_http_failed_total{job="{{ template "fullname" . }}", code!~"4[0-9]{2}"}[5m])) / sum by(method) (rate(etcd_http_received_total{job="{{ template "fullname" . }}"}[5m])) > 0.01
      FOR 10m
      LABELS {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "a high number of HTTP requests are failing",
        description = "{{`{{ $value }}`}}% of requests for {{`{{ $labels.method }}`}} failed on etcd instance {{`{{ $labels.instance }}`}}",
      }

    # alert if more than 5% of requests to an HTTP endpoint have failed with a non 4xx response
    ALERT HighNumberOfFailedHTTPRequests
      IF sum by(method) (rate(etcd_http_failed_total{job="{{ template "fullname" . }}", code!~"4[0-9]{2}"}[5m])) / sum by(method) (rate(etcd_http_received_total{job="{{ template "fullname" . }}"}[5m])) > 0.05
      FOR 5m
      LABELS {
        severity = "critical"
      }
      ANNOTATIONS
      {
        summary = "a high number of HTTP requests are failing",
        description = "{{`{{ $value }}`}}% of requests for {{`{{ $labels.method }}`}} failed on etcd instance {{`{{ $labels.instance }}`}}",
      }

    # alert if 50% of requests get a 4xx response
    ALERT HighNumberOfFailedHTTPRequests
      IF sum by(method) (rate(etcd_http_failed_total{job="{{ template "fullname" . }}", code=~"4[0-9]{2}"}[5m])) / sum by(method) (rate(etcd_http_received_total{job="{{ template "fullname" . }}"}[5m])) > 0.5
      FOR 10m
      LABELS {
        severity = "critical"
      }
      ANNOTATIONS
      {
        summary = "a high number of HTTP requests are failing",
        description = "{{`{{ $value }}`}}% of requests for {{`{{ $labels.method }}`}} failed with 4xx responses on etcd instance {{`{{ $labels.instance }}`}}",
      }

    # alert if the 99th percentile of HTTP requests take more than 150ms
    ALERT HTTPRequestsSlow
      IF histogram_quantile(0.99, rate(etcd_http_successful_duration_second_bucket[5m])) > 0.15
      FOR 10m
      LABELS
      {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "slow HTTP requests",
        description = "on ectd instance {{`{{ $labels.instance }}`}} HTTP requests to {{`{{ $labels.method }}`}} are slow",
      }

    ALERT K8SApiServerEtcdAccessLatency
      IF etcd_request_latencies_summary{quantile="0.99"} / 1e6 > 1.0
      FOR 15m
      LABELS {
        service = "k8s",
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "Access to etcd is slow",
        description = "99th percentile latency for apiserver to access etcd is higher than 1s.",
      }

    ### etcd proposal alerts ###

    # alert if there are several failed proposals within an hour
    ALERT HighNumberOfFailedProposals
      IF increase(etcd_server_proposal_failed_total{job="{{ template "fullname" . }}"}[1h]) > 5
      LABELS {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "a high number of failed proposals within the etcd cluster are happening",
        description = "etcd instance {{`{{ $labels.instance }}`}} has seen {{`{{ $value }}`}} proposal failures within the last hour",
      }

    ### etcd disk io latency alerts

    # alert if 99th percentile of fsync durations is higher than 500ms
    ALERT HighFsyncDurations
      IF histogram_quantile(0.99, rate(etcd_wal_fsync_durations_seconds_bucket[5m])) > 0.5
      FOR 10m
      LABELS {
        severity = "warning"
      }
      ANNOTATIONS {
        summary = "high fsync durations",
        description = "ectd instance {{`{{ $labels.instance }}`}} fync durations are high",
      }
