apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-coredns.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.selectorLabel }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}
  name: {{ template "exporter-coredns.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: {{ template "exporter-coredns.name" . }}
      component: {{ .Values.selectorLabel }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics-coredns
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
