apiVersion: v1
description: A Helm chart for Kubernetes
name: exporter-kube-etcd
version: 0.1.11
maintainers:
  - name: Michael Goodness
    email: mgoodness@gmail.com
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
