# on what port are the metrics exposed by etcd. Use port 2379 for https
etcdPort:  4001
# for deployments that have etcd deployed outside of the cluster, list their adresses here
endpoints: [] 
# Are we talking http or https?
scheme: http
# default rules are in templates/etcd3.rules.yaml
# prometheusRules: {}

# TLS Cofiguration for the service monitor, default to none, but append cert and keyfile if passed
caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
certFile: ""
keyFile: ""
