name: release
on:
  release:
    types:
      - created

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    name: Upload release assets
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ env.golang-version }}'
          check-latest: true
      - name: Upload bundle.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bundle.yaml
          asset_name: bundle.yaml
          tag: ${{ github.ref }}
          overwrite: true
      - name: Generate stripped down version of CRDs
        run: make stripped-down-crds.yaml
      - name: Upload stripped-down-crds.yaml to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: stripped-down-crds.yaml
          asset_name: stripped-down-crds.yaml
          tag: ${{ github.ref }}
          overwrite: true
