name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had any activity in the last 60 days. Thank you for your contributions.'
          close-issue-message: 'This issue was closed because it has not had any activity in the last 120 days. Please reopen if you feel this is still valid.'
          days-before-stale: 60
          days-before-issue-close: 120
          days-before-pr-close: -1  # Prevent closing PRs
          exempt-issue-labels: 'kind/feature,help-wanted,kind/bug'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-draft-pr: true
